export interface Solution {
  // ex: Todolist
  name: string

  // ex: MyCompany.Todolist
  path: string

  // TODO: semantic versioning
  // ex: 1.0.0
  version: string

  meta: {
    // ex: MyCompany
    organization: string
    createdAt: Date
  }
}

export interface Config {
  author: {
    // ex: Philippe Matray
    name: string
  }

  // list of solution configs generated by ninjacat
  solutions: Solution[]
}
