export type AttributeType = 'int' | 'string' | 'date'

export interface EntityAttribute {
  name: string
  type: AttributeType
  required: true
}

export interface Entity {
  info: {
    name: string
    description: string
  }
  options: {
    timestamps: true
  }
  attributes: EntityAttribute[]
}

export interface Solution {
  // ex: Todolist
  name: string

  // ex: MyCompany.Todolist
  path: string

  // TODO: semantic versioning
  // ex: 1.0.0
  version: string

  meta: {
    // ex: MyCompany
    organization: string
    createdAt: Date
  }

  entities: Entity[]
}

export interface Config {
  author: {
    // ex: Philippe Matray
    name: string
  }

  // list of solution configs generated by ninjacat
  solutions: Solution[]
}
